title: Advances in Micro-ElectroMechanical System (MEMS)
author: Masood-Ur-Rehman
email: msd_555@rocketmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'll talk about the advanced applications using MEMS devices.

# social links
twitter_username:masood3333 # DO NOT include the @ character, or else the build will fail!
github_username:  masood3333 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
Theme: minima
